modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "shieldsoundsbackport"
version = "${version}"
displayName = "Shield Sounds Backport"
authors = "Noryea"
description = '''
A server-side mod backports shield sounds from the latest Minecraft release. (Fixes MC-255756)
'''

[[dependencies.shieldsoundsbackport]]
modId = "forge"
mandatory = true
versionRange = "[51,)"
ordering = "NONE"

[[dependencies.shieldsoundsbackport]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21,)"
ordering = "NONE"